repos:
  # Pre-commit hooks for basic checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-json
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: detect-private-key
      - id: check-builtin-literals
      - id: check-shebang-scripts-are-executable
      - id: file-contents-sorter
        files: ^(requirements\.txt|requirements-test\.txt|\.gitignore)$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.8.4
    hooks:
      # Run the linter.
      - id: ruff
        args: ["--fix", "--ignore", "E402"]
      # Run the formatter.
      - id: ruff-format

  # Mypy for type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        args: ["--ignore-missing-imports", "--explicit-package-bases"]
        exclude: tests/

  # ShellCheck
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
